name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Restore packages
        run: nuget restore
      - name: Generate contract
        run: dotnet run --project Engine/ContractGenerator
      - name: Archive contract
        uses: actions/upload-artifact@v2.2.0
        with:
          path: Library/common/contract.json
          name: Contract
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --no-build --verbosity normal
